name: First Workflow
on: workflow_dispatch

jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: echo "Hello World"
      - name: Print Goodbye
        run: echo "Bye Bye"

  build-dotnet-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x' # Set to your required version

      - name: Restore dependencies
        run: dotnet restore HelloWorld/HelloWorld.sln

      - name: Build
        run: dotnet build HelloWorld/HelloWorld.sln --no-restore --configuration Release
